Repository Azure/missionlz, pull requests merged in 2024-05, with the labels that each got.

#1020 Added parameters to deploy Bastion, Windows and Linux VMs separately.
  src/bicep/form/mlz.portal.json
  src/bicep/mlz.bicep
  src/bicep/mlz.json
  src/bicep/modules/hub-network.bicep
  src/bicep/modules/networking.bicep
  src/bicep/modules/remote-access.bicep
Labels: user interface, bicep

#1024 MLZ: Added Mike D's prereqs script
  src/bicep/artifacts/Get-PreReqs.ps1
Labels: powershell

#1038 mlz Template spec instructions
  README.md
  docs/deployment-guide-templatespec.md
Labels: documentation
