Repository Azure/missionlz, pull requests merged in 2024-08, with the labels that each got.

#1072 977 mlz optional deploy a different flavor of linux for bastion jump host
  src/bicep/form/mlz.portal.json
  src/bicep/mlz.bicep
  src/bicep/mlz.json
  src/bicep/modules/linux-virtual-machine.bicep
  src/bicep/modules/remote-access.bicep
Labels: core

#1067 919 security documentation added firewall post configs for avd
  docs/image-1.png
  docs/image-10.png
  docs/image-11.png
  docs/image-12.png
  docs/image-13.png
  docs/image-14.png
  docs/image-15.png
  docs/image-16.png
  docs/image-17.png
  docs/image-18.png
  docs/image-19.png
  docs/image-2.png
  docs/image-20.png
  docs/image-21.png
  docs/image-22.png
  docs/image-23.png
  docs/image-24.png
  docs/image-25.png
  docs/image-26.png
  docs/image-3.png
  docs/image-4.png
  docs/image-5.png
  docs/image-6.png
  docs/image-7.png
  docs/image-8.png
  docs/image-9.png
  docs/image.png
  docs/security.md
Labels: documentation

#1076 Corrected 'allowedValues' for Linux offer in UIDefinitionFile
  src/bicep/form/mlz.portal.json
  src/bicep/mlz.bicep
  src/bicep/mlz.json
Labels: bug
